import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  id: {
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.guest': 'Guest',
    'nav.admin': 'Admin',
    
    'welcome.title': 'ENTER THE',
    'welcome.subtitle': 'Platform komunitas trading modern. Akses materi eksklusif, komunitas Discord privat, dan real-time market data — semua dalam satu platform.',
    'welcome.google': 'Login dengan Google',
    'welcome.discord': 'Login dengan Discord',
    'welcome.or': 'ATAU',
    'welcome.email': 'Login dengan Email',
    'welcome.email_login': 'Login Email',
    'welcome.email_placeholder': 'email@duckstation.com',
    'welcome.password': 'Password',
    'welcome.login_btn': 'Masuk',
    'welcome.no_account': 'Belum punya akun? Hubungi admin via Discord.',
    'welcome.platform_online': 'PLATFORM ONLINE',
    'welcome.secure': 'Secure Auth',
    'welcome.realtime': 'Real-time Data',
    'welcome.community': 'Discord Community',
    'welcome.back': 'Kembali',
    
    'dash.modules': 'Modul Materi',
    'dash.modules_desc': 'Kurikulum berjenjang — selesaikan quiz & belajar secara sistematis.',
    'dash.how_to': 'Cara Memulai',
    'dash.free': 'GRATIS',
    'dash.premium': 'Premium',
    'dash.lessons': 'lessons',
    'dash.batch': 'Batch',
    'dash.start_learning': 'Mulai Belajar',
    'dash.locked': 'Terkunci',
    'dash.no_modules': 'Belum ada modul materi',
    'dash.loading': 'Memuat modul...',
    'dash.guest_banner': 'Anda masih guest. Bergabung dengan kelas untuk membuka semua materi.',
    'dash.join_class': 'Pilih Kelas',
    'dash.sidebar_modules': 'Modul Materi',
    'dash.sidebar_howto': 'Cara Memulai',
    'dash.sidebar_batches': 'Pilih Kelas / Batch',
    'dash.sidebar_booking': 'Booking 1-on-1',
    'dash.sidebar_homework': 'Homework & Quiz',
    'dash.sidebar_journal': 'Trading Journal',
    'dash.sidebar_tickets': 'Private Ticketing',
    'dash.sidebar_messages': 'Pesan Admin',
    'dash.sidebar_settings': 'Pengaturan Akun',
    
    'settings.title': 'Pengaturan Akun',
    'settings.desc': 'Kelola profil, integrasi Web3, dan binding Discord Anda di sini.',
    'settings.profile': 'Profil & Kontak',
    'settings.name': 'Nama',
    'settings.email': 'Email',
    'settings.telegram': 'Username Telegram',
    'settings.telegram_hint': 'Wajib untuk komunikasi Admin',
    'settings.experience': 'Pengalaman Trading',
    'settings.exp_pemula': 'Pemula (belum pernah trading)',
    'settings.exp_beginner': 'Beginner (sudah coba tapi belum konsisten)',
    'settings.exp_intermediate': 'Intermediate (sudah beberapa bulan)',
    'settings.save': 'Simpan Profil',
    'settings.saving': 'Menyimpan...',
    'settings.saved': 'Profil berhasil disimpan!',
    'settings.discord_title': 'Integrasi Discord',
    'settings.discord_hint': 'Wajib untuk akses grup kelas',
    'settings.discord_authorize': 'Authorize Discord',
    'settings.subscription': 'Status Subscription',
    'settings.role': 'Role',
    'settings.expires': 'Berakhir',
    'settings.remaining': 'Sisa',
    'settings.days': 'hari',
    'settings.no_sub': 'Belum subscribe',
    
    'batch.title': 'Pilih Kelas / Batch',
    'batch.desc': 'Pilih batch yang sesuai. Setelah memilih, kamu akan mengisi formulir pendaftaran dan melakukan pembayaran.',
    'batch.enroll': 'Daftar Batch Ini',
    'batch.popular': 'Terpopuler',
    
    'booking.title': 'Booking Sesi 1-on-1',
    'booking.desc': 'Jadwalkan sesi privat dengan mentor. Kuota terbatas.',
    'booking.quota': 'Kuota Terbatas',
    'booking.remaining': 'Sisa',
    'booking.slots': 'slot',
    'booking.pick_date': 'Pilih Tanggal',
    'booking.pick_time': 'Pilih Jam',
    'booking.select_date_first': 'Pilih tanggal terlebih dahulu',
    'booking.loading': 'Memuat slot waktu...',
    'booking.no_slots': 'Tidak ada slot tersedia untuk tanggal ini.',
    'booking.available': 'Tersedia',
    'booking.booked': 'Terbooking',
    'booking.confirm': 'Konfirmasi Booking',
    'booking.processing': 'Memproses...',
    'booking.success': 'Booking berhasil! Menunggu konfirmasi admin.',
    'booking.failed': 'Gagal membuat booking.',
    'booking.full': 'Kuota penuh',
    
    'hw.title': 'Homework & Quiz',
    'hw.desc': 'Selesaikan tugas wajib untuk membuka modul berikutnya. Skor minimum: 70.',
    'hw.total': 'Total Tugas',
    'hw.done': 'Selesai',
    'hw.pending': 'Perlu Dikerjakan',
    'hw.pending_tab': 'Pending & Retake',
    'hw.done_tab': 'Selesai',
    'hw.all_done': 'Semua tugas selesai!',
    'hw.great': 'Kerja bagus!',
    'hw.start': 'Mulai Kerjakan',
    'hw.retake': 'Retake',
    'hw.view_answer': 'Lihat Jawaban',
    'hw.score': 'Skor',
    'hw.min_score': 'Skor Minimum',
    
    'journal.title': 'Trading Journal',
    'journal.new_account': 'Akun Baru',
    'journal.new_trade': 'Trade Baru',
    'journal.total_pnl': 'Total PnL',
    'journal.win_rate': 'Win Rate',
    'journal.total_trades': 'Total Trades',
    'journal.balance': 'Saldo',
    'journal.equity_curve': 'Equity Curve',
    'journal.calendar': 'Calendar PnL',
    'journal.entries': 'Daftar Trade',
    'journal.no_entries': 'Belum ada trade.',
    'journal.no_accounts': 'Buat akun trading terlebih dahulu.',
    'journal.pair': 'Pair',
    'journal.timeframe': 'Timeframe',
    'journal.direction': 'Direction',
    'journal.buy': 'Buy',
    'journal.sell': 'Sell',
    'journal.entry_price': 'Entry Price',
    'journal.exit_price': 'Exit Price',
    'journal.risk': 'Risk',
    'journal.pnl': 'PnL',
    'journal.reason': 'Alasan Trade',
    'journal.notes': 'Catatan',
    'journal.images': 'Gambar',
    'journal.result': 'Hasil',
    'journal.win': 'Win',
    'journal.loss': 'Loss',
    'journal.breakeven': 'Breakeven',
    'journal.pending_result': 'Pending',
    'journal.save': 'Simpan',
    'journal.cancel': 'Batal',
    'journal.delete': 'Hapus',
    'journal.delete_confirm': 'Yakin hapus trade ini?',
    'journal.account_name': 'Nama Akun',
    'journal.account_type': 'Tipe Akun',
    'journal.personal': 'Personal',
    'journal.funded': 'Funded',
    'journal.custom': 'Custom',
    'journal.balance_start': 'Balance Awal',
    'journal.broker': 'Broker',
    'journal.delete_account': 'Hapus Akun',
    'journal.delete_account_confirm': 'Yakin hapus akun ini? Semua trade terkait akan dihapus.',
    
    'msg.title': 'Pesan Admin',
    'msg.no_messages': 'Belum ada pesan.',
    'msg.from': 'Dari',
    'msg.delete': 'Hapus',
    
    'ticket.title': 'Private Ticketing',
    'ticket.new': 'Tiket Baru',
    'ticket.search': 'Cari tiket...',
    'ticket.select': 'Pilih tiket untuk melihat percakapan',
    'ticket.placeholder': 'Ketik pesan Anda...',
    'ticket.sending': 'Mengirim...',
    
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcome': 'Selamat datang kembali. Berikut ringkasan hari ini.',
    'admin.new_orders': 'Order Baru',
    'admin.pending': 'Menunggu approval',
    'admin.total_members': 'Total Member',
    'admin.total_registered': 'Total terdaftar',
    'admin.revenue': 'Revenue Bulan Ini',
    'admin.open_tickets': 'Tiket Open',
    'admin.need_reply': 'Butuh balasan admin',
    'admin.recent_orders': 'Order Terbaru',
    'admin.activity': 'Aktivitas Terkini',
    
    'module.back': 'Kembali ke Modul',
    'module.lessons_list': 'Daftar Lesson',
    'module.step': 'LANGKAH',
    'module.text': 'Teks',
    'module.image': 'Gambar',
    'module.prev': 'Lesson Sebelumnya',
    'module.next': 'Lesson Selanjutnya',
    'module.select_lesson': 'Pilih lesson dari sidebar untuk mulai belajar',
    
    'howto.title': 'Cara Memulai',
    'howto.desc': 'Ikuti setiap langkah di bawah secara berurutan untuk memulai perjalanan trading kamu.',
    'howto.step1': 'Daftar & Bayar',
    'howto.step1_desc': 'Isi form pendaftaran & lakukan pembayaran via QRIS atau Transfer.',
    'howto.step2': 'Menunggu Admin',
    'howto.step2_desc': 'Admin verifikasi pembayaran & approve pendaftaran kamu.',
    'howto.step3': 'Kerjakan Quiz',
    'howto.step3_desc': 'Quiz wajib sebelum akses materi. Min. skor 70, maks 3x percobaan.',
    'howto.step4': 'Mulai Belajar',
    'howto.step4_desc': 'Akses modul materi berjenjang & kerjakan tugas.',
    'howto.step5': 'Booking Mentor',
    'howto.step5_desc': 'Jadwalkan sesi 1-on-1 dengan mentor untuk review quiz & materi.',
    'howto.quiz_title': 'Quiz Pengetahuan Dasar Trading',
    'howto.quiz_desc': 'Quiz wajib sebelum akses materi. Min. skor 70, maks 3x percobaan.',
    'howto.passed': 'LULUS',
    'howto.start_quiz': 'Mulai Quiz Sekarang',
    'howto.retake_quiz': 'Retake Quiz',
    'howto.score_last': 'Skor terakhir',
    'howto.minimum': 'Minimum',
    'howto.remaining_attempts': 'Sisa',
    'howto.attempts_left': 'lagi',
    'howto.failed_reset': 'Gagal 3x — Semua Progres Di-Reset',
    'howto.failed_desc': 'Batas percobaan habis. Semua progres materi dan tugas di-reset.',
    'howto.reset': 'Reset & Mulai Ulang dari Awal',
    'howto.quiz_rules': 'Aturan: 10 soal • Min. skor 70 • Maks. 3 percobaan • Gagal 3x = reset dari awal',
    'howto.hw': 'Homework & Quiz',
    'howto.hw_desc': 'Kerjakan tugas & quiz wajib',
    'howto.booking': 'Booking 1-on-1',
    'howto.booking_desc': 'Jadwalkan sesi dengan mentor',
    'howto.ticketing': 'Private Ticketing',
    'howto.ticketing_desc': 'Konsultasi privat dengan admin',
    
    'enroll.terms': 'Syarat & Ketentuan',
    'enroll.terms_desc': 'Baca dan pahami seluruh syarat sebelum melanjutkan pendaftaran',
    'enroll.agree': 'Saya telah membaca, memahami, dan menyetujui seluruh syarat dan ketentuan di atas.',
    'enroll.next': 'Setuju & Lanjutkan',
    'enroll.profile': 'Data Diri',
    'enroll.profile_desc': 'Isi data diri kamu dengan benar.',
    'enroll.fullname': 'Nama Lengkap',
    'enroll.email': 'Email',
    'enroll.telegram': 'Username Telegram',
    'enroll.telegram_hint': 'Admin akan menghubungi kamu di Telegram.',
    'enroll.experience': 'Pengalaman Trading',
    'enroll.continue': 'Lanjutkan',
    'enroll.back': 'Kembali',
    'enroll.discord': 'Binding Discord',
    'enroll.discord_desc': 'Hubungkan akun Discord kamu. Wajib agar Role eksklusif otomatis diberikan.',
    'enroll.discord_account': 'Discord Akun',
    'enroll.discord_hint': 'Wajib diisi',
    'enroll.discord_not-linked': 'Belum terhubung',
    'enroll.discord_linked': 'Terhubung',
    'enroll.discord_warn': 'Discord wajib dihubungkan agar Role kelas dapat diberikan secara otomatis.',
    'enroll.confirm': 'Konfirmasi',
    'enroll.confirm_desc': 'Pastikan data sudah benar sebelum mengirim pendaftaran.',
    'enroll.summary': 'Ringkasan & Konfirmasi',
    'enroll.send': 'Kirim Pendaftaran',
    'enroll.success': 'Pendaftaran Diterima!',
    'enroll.success_desc': 'Admin akan menghubungi kamu via Telegram dalam 1x24 jam untuk konfirmasi pembayaran.',
    'enroll.status': 'Menunggu Konfirmasi Admin',
    'enroll.payment_steps': 'Cara Pembayaran',
    'enroll.payment_1': 'Klik "Kirim Pendaftaran" di bawah',
    'enroll.payment_2': 'Admin menghubungi via Telegram dalam 1x24 jam',
    'enroll.payment_3': 'Admin mengirimkan QRIS / nomor rekening',
    'enroll.payment_4': 'Lakukan transfer & kirim bukti',
    'enroll.payment_5': 'Admin approve → akses & Discord Role aktif',
    
    'landing.system_online': 'SYSTEM ONLINE • MARKET OPEN',
    'landing.hero_title': 'THE ELITE',
    'landing.hero_subtitle': 'TRADING COMMUNITY.',
    'landing.hero_desc': 'Bukan sekadar edukasi, ini adalah ekosistem. Bergabunglah dengan ribuan trader pro di Discord eksklusif kami.',
    'landing.enter_dashboard': 'ENTER DASHBOARD',
    'landing.view_market': 'View Market Analytics',
    'landing.features_title': 'Kenapa DuckStation?',
    'landing.features_badge': 'Fitur Unggulan',
    'landing.how_it_works': 'Cara Bergabung',
    'landing.how_badge': 'Langkah Mudah',
    'landing.testimonials': 'Apa Kata Mereka',
    'landing.testimonials_badge': 'Testimoni',
    'landing.faq': 'Pertanyaan Umum',
    'landing.faq_badge': 'Tanya Jawab',
    'landing.cta_title': 'Siap Memulai Perjalanan Trading Kamu?',
    'landing.cta_desc': 'Bergabung sekarang dan dapatkan akses ke materi eksklusif, komunitas privat, dan bimbingan mentor profesional.',
    'landing.cta_btn': 'MULAI SEKARANG',
    'landing.terms': 'Terms',
    'landing.privacy': 'Privacy',
    'landing.discord_link': 'Discord',
    'landing.twitter': 'Twitter',
    
    'common.loading': 'Loading...',
    'common.error': 'Terjadi kesalahan',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.add': 'Tambah',
    'common.search': 'Cari...',
    'common.all': 'Semua',
    'common.close': 'Tutup',
    'common.confirm': 'Konfirmasi',
    'common.back': 'Kembali',
    'common.next': 'Selanjutnya',
    'common.prev': 'Sebelumnya',
    'common.days': 'hari',
    'common.active': 'Aktif',
    'common.inactive': 'Tidak Aktif',
    'common.open': 'Open',
    'common.closed': 'Closed',
  },
  
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.guest': 'Guest',
    'nav.admin': 'Admin',
    
    'welcome.title': 'ENTER THE',
    'welcome.subtitle': 'Modern trading community platform. Access exclusive materials, private Discord community, and real-time market data — all in one platform.',
    'welcome.google': 'Login with Google',
    'welcome.discord': 'Login with Discord',
    'welcome.or': 'OR',
    'welcome.email': 'Login with Email',
    'welcome.email_login': 'Email Login',
    'welcome.email_placeholder': 'email@duckstation.com',
    'welcome.password': 'Password',
    'welcome.login_btn': 'Sign In',
    'welcome.no_account': "Don't have an account? Contact admin via Discord.",
    'welcome.platform_online': 'PLATFORM ONLINE',
    'welcome.secure': 'Secure Auth',
    'welcome.realtime': 'Real-time Data',
    'welcome.community': 'Discord Community',
    'welcome.back': 'Back',
    
    'dash.modules': 'Course Modules',
    'dash.modules_desc': 'Structured curriculum — complete quizzes & learn systematically.',
    'dash.how_to': 'How to Start',
    'dash.free': 'FREE',
    'dash.premium': 'Premium',
    'dash.lessons': 'lessons',
    'dash.batch': 'Batch',
    'dash.start_learning': 'Start Learning',
    'dash.locked': 'Locked',
    'dash.no_modules': 'No modules available yet',
    'dash.loading': 'Loading modules...',
    'dash.guest_banner': "You're still a guest. Join a class to unlock all materials.",
    'dash.join_class': 'Browse Classes',
    'dash.sidebar_modules': 'Course Modules',
    'dash.sidebar_howto': 'How to Start',
    'dash.sidebar_batches': 'Browse Classes',
    'dash.sidebar_booking': 'Booking 1-on-1',
    'dash.sidebar_homework': 'Homework & Quiz',
    'dash.sidebar_journal': 'Trading Journal',
    'dash.sidebar_tickets': 'Private Ticketing',
    'dash.sidebar_messages': 'Admin Messages',
    'dash.sidebar_settings': 'Account Settings',
    
    'settings.title': 'Account Settings',
    'settings.desc': 'Manage your profile, integrations, and Discord binding here.',
    'settings.profile': 'Profile & Contact',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.telegram': 'Telegram Username',
    'settings.telegram_hint': 'Required for admin communication',
    'settings.experience': 'Trading Experience',
    'settings.exp_pemula': 'Beginner (never traded)',
    'settings.exp_beginner': 'Intermediate (tried but inconsistent)',
    'settings.exp_intermediate': 'Advanced (several months)',
    'settings.save': 'Save Profile',
    'settings.saving': 'Saving...',
    'settings.saved': 'Profile saved successfully!',
    'settings.discord_title': 'Discord Integration',
    'settings.discord_hint': 'Required for class access',
    'settings.discord_authorize': 'Authorize Discord',
    'settings.subscription': 'Subscription Status',
    'settings.role': 'Role',
    'settings.expires': 'Expires',
    'settings.remaining': 'Remaining',
    'settings.days': 'days',
    'settings.no_sub': 'No subscription yet',
    
    'batch.title': 'Browse Classes',
    'batch.desc': 'Choose a batch that suits you. After selecting, you will fill out the registration form and make a payment.',
    'batch.enroll': 'Enroll Now',
    'batch.popular': 'Most Popular',
    
    'booking.title': 'Booking 1-on-1 Session',
    'booking.desc': 'Schedule a private session with a mentor. Limited quota.',
    'booking.quota': 'Limited Quota',
    'booking.remaining': 'Remaining',
    'booking.slots': 'slots',
    'booking.pick_date': 'Pick a Date',
    'booking.pick_time': 'Pick a Time',
    'booking.select_date_first': 'Select a date first',
    'booking.loading': 'Loading time slots...',
    'booking.no_slots': 'No slots available for this date.',
    'booking.available': 'Available',
    'booking.booked': 'Booked',
    'booking.confirm': 'Confirm Booking',
    'booking.processing': 'Processing...',
    'booking.success': 'Booking successful! Waiting for admin confirmation.',
    'booking.failed': 'Failed to create booking.',
    'booking.full': 'Quota full',
    
    'hw.title': 'Homework & Quiz',
    'hw.desc': 'Complete mandatory tasks to unlock the next module. Minimum score: 70.',
    'hw.total': 'Total Tasks',
    'hw.done': 'Completed',
    'hw.pending': 'To Do',
    'hw.pending_tab': 'Pending & Retake',
    'hw.done_tab': 'Completed',
    'hw.all_done': 'All tasks completed!',
    'hw.great': 'Great job!',
    'hw.start': 'Start',
    'hw.retake': 'Retake',
    'hw.view_answer': 'View Answer',
    'hw.score': 'Score',
    'hw.min_score': 'Minimum Score',
    
    'journal.title': 'Trading Journal',
    'journal.new_account': 'New Account',
    'journal.new_trade': 'New Trade',
    'journal.total_pnl': 'Total PnL',
    'journal.win_rate': 'Win Rate',
    'journal.total_trades': 'Total Trades',
    'journal.balance': 'Balance',
    'journal.equity_curve': 'Equity Curve',
    'journal.calendar': 'Calendar PnL',
    'journal.entries': 'Trade History',
    'journal.no_entries': 'No trades yet.',
    'journal.no_accounts': 'Create a trading account first.',
    'journal.pair': 'Pair',
    'journal.timeframe': 'Timeframe',
    'journal.direction': 'Direction',
    'journal.buy': 'Buy',
    'journal.sell': 'Sell',
    'journal.entry_price': 'Entry Price',
    'journal.exit_price': 'Exit Price',
    'journal.risk': 'Risk',
    'journal.pnl': 'PnL',
    'journal.reason': 'Trade Reason',
    'journal.notes': 'Notes',
    'journal.images': 'Images',
    'journal.result': 'Result',
    'journal.win': 'Win',
    'journal.loss': 'Loss',
    'journal.breakeven': 'Breakeven',
    'journal.pending_result': 'Pending',
    'journal.save': 'Save',
    'journal.cancel': 'Cancel',
    'journal.delete': 'Delete',
    'journal.delete_confirm': 'Delete this trade?',
    'journal.account_name': 'Account Name',
    'journal.account_type': 'Account Type',
    'journal.personal': 'Personal',
    'journal.funded': 'Funded',
    'journal.custom': 'Custom',
    'journal.balance_start': 'Starting Balance',
    'journal.broker': 'Broker',
    'journal.delete_account': 'Delete Account',
    'journal.delete_account_confirm': 'Delete this account? All related trades will be removed.',
    
    'msg.title': 'Admin Messages',
    'msg.no_messages': 'No messages yet.',
    'msg.from': 'From',
    'msg.delete': 'Delete',
    
    'ticket.title': 'Private Ticketing',
    'ticket.new': 'New Ticket',
    'ticket.search': 'Search tickets...',
    'ticket.select': 'Select a ticket to view conversation',
    'ticket.placeholder': 'Type your message...',
    'ticket.sending': 'Sending...',
    
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcome': 'Welcome back. Here is today\'s summary.',
    'admin.new_orders': 'New Orders',
    'admin.pending': 'Awaiting approval',
    'admin.total_members': 'Total Members',
    'admin.total_registered': 'Total registered',
    'admin.revenue': 'Monthly Revenue',
    'admin.open_tickets': 'Open Tickets',
    'admin.need_reply': 'Need admin reply',
    'admin.recent_orders': 'Recent Orders',
    'admin.activity': 'Recent Activity',
    
    'module.back': 'Back to Modules',
    'module.lessons_list': 'Lesson List',
    'module.step': 'STEP',
    'module.text': 'Text',
    'module.image': 'Image',
    'module.prev': 'Previous Lesson',
    'module.next': 'Next Lesson',
    'module.select_lesson': 'Select a lesson from the sidebar to start learning',
    
    'howto.title': 'How to Start',
    'howto.desc': 'Follow each step below in order to start your trading journey.',
    'howto.step1': 'Register & Pay',
    'howto.step1_desc': 'Fill out the registration form and make payment via QRIS or bank transfer.',
    'howto.step2': 'Wait for Admin',
    'howto.step2_desc': 'Admin verifies payment and approves your registration.',
    'howto.step3': 'Take the Quiz',
    'howto.step3_desc': 'Quiz required before accessing materials. Min. score 70, max 3 attempts.',
    'howto.step4': 'Start Learning',
    'howto.step4_desc': 'Access structured course modules and complete assignments.',
    'howto.step5': 'Book Mentor',
    'howto.step5_desc': 'Schedule a 1-on-1 session with a mentor for quiz and material review.',
    'howto.quiz_title': 'Basic Trading Knowledge Quiz',
    'howto.quiz_desc': 'Required quiz before accessing materials. Min. score 70, max 3 attempts.',
    'howto.passed': 'PASSED',
    'howto.start_quiz': 'Start Quiz Now',
    'howto.retake_quiz': 'Retake Quiz',
    'howto.score_last': 'Last score',
    'howto.minimum': 'Minimum',
    'howto.remaining_attempts': 'Remaining',
    'howto.attempts_left': 'left',
    'howto.failed_reset': 'Failed 3x — All Progress Reset',
    'howto.failed_desc': 'Attempts exhausted. All course progress and tasks will be reset.',
    'howto.reset': 'Reset & Start Over',
    'howto.quiz_rules': 'Rules: 10 questions • Min. score 70 • Max. 3 attempts • Failed 3x = reset from start',
    'howto.hw': 'Homework & Quiz',
    'howto.hw_desc': 'Complete mandatory tasks & quizzes',
    'howto.booking': 'Booking 1-on-1',
    'howto.booking_desc': 'Schedule a session with a mentor',
    'howto.ticketing': 'Private Ticketing',
    'howto.ticketing_desc': 'Private consultation with admin',
    
    'enroll.terms': 'Terms & Conditions',
    'enroll.terms_desc': 'Read and understand all terms before continuing registration',
    'enroll.agree': 'I have read, understood, and agree to all terms and conditions above.',
    'enroll.next': 'Agree & Continue',
    'enroll.profile': 'Personal Data',
    'enroll.profile_desc': 'Fill in your personal data correctly.',
    'enroll.fullname': 'Full Name',
    'enroll.email': 'Email',
    'enroll.telegram': 'Telegram Username',
    'enroll.telegram_hint': 'Admin will contact you via Telegram.',
    'enroll.experience': 'Trading Experience',
    'enroll.continue': 'Continue',
    'enroll.back': 'Back',
    'enroll.discord': 'Discord Binding',
    'enroll.discord_desc': 'Connect your Discord account. Required for automatic exclusive role assignment.',
    'enroll.discord_account': 'Discord Account',
    'enroll.discord_hint': 'Required',
    'enroll.discord_not-linked': 'Not connected',
    'enroll.discord_linked': 'Connected',
    'enroll.discord_warn': 'Discord must be connected so class role can be automatically assigned.',
    'enroll.confirm': 'Confirmation',
    'enroll.confirm_desc': 'Make sure all data is correct before submitting registration.',
    'enroll.summary': 'Summary & Confirmation',
    'enroll.send': 'Submit Registration',
    'enroll.success': 'Registration Accepted!',
    'enroll.success_desc': 'Admin will contact you via Telegram within 24 hours for payment confirmation.',
    'enroll.status': 'Awaiting Admin Confirmation',
    'enroll.payment_steps': 'Payment Instructions',
    'enroll.payment_1': 'Click "Submit Registration" below',
    'enroll.payment_2': 'Admin contacts you via Telegram within 24 hours',
    'enroll.payment_3': 'Admin sends QRIS / bank account number',
    'enroll.payment_4': 'Make transfer & send proof',
    'enroll.payment_5': 'Admin approves → access & Discord Role activated',
    
    'landing.system_online': 'SYSTEM ONLINE • MARKET OPEN',
    'landing.hero_title': 'THE ELITE',
    'landing.hero_subtitle': 'TRADING COMMUNITY.',
    'landing.hero_desc': 'Not just education, this is an ecosystem. Join thousands of pro traders in our exclusive Discord.',
    'landing.enter_dashboard': 'ENTER DASHBOARD',
    'landing.view_market': 'View Market Analytics',
    'landing.features_title': 'Why DuckStation?',
    'landing.features_badge': 'Key Features',
    'landing.how_it_works': 'How to Join',
    'landing.how_badge': 'Easy Steps',
    'landing.testimonials': 'What They Say',
    'landing.testimonials_badge': 'Testimonials',
    'landing.faq': 'Frequently Asked Questions',
    'landing.faq_badge': 'FAQ',
    'landing.cta_title': 'Ready to Start Your Trading Journey?',
    'landing.cta_desc': 'Join now and get access to exclusive materials, private community, and professional mentor guidance.',
    'landing.cta_btn': 'GET STARTED',
    'landing.terms': 'Terms',
    'landing.privacy': 'Privacy',
    'landing.discord_link': 'Discord',
    'landing.twitter': 'Twitter',
    
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search...',
    'common.all': 'All',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.prev': 'Previous',
    'common.days': 'days',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.open': 'Open',
    'common.closed': 'Closed',
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'id');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['id']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
